In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [7]:
embedding = nn.Embedding(10, 3)
input = torch.LongTensor([[[1,2,4,5],[4,3,2,9]],[[1,2,4,5],[4,3,2,9]]])
Cc = embedding(input)
Cc.size()

torch.Size([2, 2, 4, 3])

In [9]:
torch.max(Cc, dim=2)[0].size()

torch.Size([2, 2, 3])

In [4]:
F.softmax(o, dim=0)

tensor([[ 0.9323,  0.0024,  0.2596,  0.0099,  0.0339],
        [ 0.0011,  0.9499,  0.0101,  0.1193,  0.0024],
        [ 0.0505,  0.0043,  0.4436,  0.1324,  0.0813],
        [ 0.0016,  0.0412,  0.1088,  0.5778,  0.0603],
        [ 0.0144,  0.0022,  0.1779,  0.1606,  0.8222]])

In [5]:
F.softmax(o, dim=1)

tensor([[ 0.9323,  0.0011,  0.0505,  0.0016,  0.0144],
        [ 0.0024,  0.9499,  0.0043,  0.0412,  0.0022],
        [ 0.2596,  0.0101,  0.4436,  0.1088,  0.1779],
        [ 0.0099,  0.1193,  0.1324,  0.5778,  0.1606],
        [ 0.0339,  0.0024,  0.0813,  0.0603,  0.8222]])

In [9]:
x = torch.arange(10).unsqueeze(dim=1)
y = torch.rand(3, 10, 5)
y

tensor([[[ 0.0568,  0.7597,  0.4587,  0.5394,  0.8227],
         [ 0.2031,  0.6341,  0.2812,  0.7192,  0.2875],
         [ 0.2333,  0.4712,  0.1009,  0.8033,  0.5396],
         [ 0.6620,  0.5866,  0.6243,  0.8124,  0.0117],
         [ 0.2882,  0.3431,  0.7884,  0.3070,  0.5795],
         [ 0.0270,  0.7944,  0.1497,  0.5959,  0.9007],
         [ 0.7411,  0.2880,  0.6324,  0.1191,  0.8027],
         [ 0.8602,  0.2230,  0.2809,  0.9650,  0.7901],
         [ 0.2668,  0.8183,  0.2902,  0.5532,  0.8453],
         [ 0.4725,  0.1735,  0.5083,  0.7119,  0.7976]],

        [[ 0.0076,  0.3758,  0.3372,  0.1796,  0.3254],
         [ 0.1105,  0.6278,  0.7164,  0.5588,  0.3236],
         [ 0.1278,  0.1908,  0.4959,  0.9034,  0.0444],
         [ 0.5738,  0.8094,  0.7876,  0.9768,  0.4815],
         [ 0.1434,  0.8850,  0.9540,  0.3217,  0.6866],
         [ 0.3695,  0.1170,  0.0543,  0.7396,  0.2044],
         [ 0.5912,  0.5735,  0.9189,  0.6315,  0.3125],
         [ 0.9882,  0.0999,  0.0109,  0.8472, 

In [10]:
torch.add(y, x)

tensor([[[ 0.0568,  0.7597,  0.4587,  0.5394,  0.8227],
         [ 1.2031,  1.6341,  1.2812,  1.7192,  1.2875],
         [ 2.2333,  2.4712,  2.1009,  2.8033,  2.5396],
         [ 3.6620,  3.5866,  3.6243,  3.8124,  3.0117],
         [ 4.2882,  4.3431,  4.7884,  4.3070,  4.5795],
         [ 5.0270,  5.7944,  5.1497,  5.5959,  5.9007],
         [ 6.7411,  6.2880,  6.6324,  6.1191,  6.8027],
         [ 7.8602,  7.2230,  7.2809,  7.9650,  7.7901],
         [ 8.2668,  8.8183,  8.2902,  8.5532,  8.8453],
         [ 9.4725,  9.1735,  9.5083,  9.7119,  9.7976]],

        [[ 0.0076,  0.3758,  0.3372,  0.1796,  0.3254],
         [ 1.1105,  1.6278,  1.7164,  1.5588,  1.3236],
         [ 2.1278,  2.1908,  2.4959,  2.9034,  2.0444],
         [ 3.5738,  3.8094,  3.7876,  3.9768,  3.4815],
         [ 4.1434,  4.8850,  4.9540,  4.3217,  4.6866],
         [ 5.3695,  5.1170,  5.0543,  5.7396,  5.2044],
         [ 6.5912,  6.5735,  6.9189,  6.6315,  6.3125],
         [ 7.9882,  7.0999,  7.0109,  7.8472, 

In [11]:
import matplotlib.pyplot as plt

In [22]:
c = torch.arange(5)
q = torch.arange(5)
torch.cat([q, c, torch.mul(q, c)], dim=0)

tensor([  0.,   1.,   2.,   3.,   4.,   0.,   1.,   2.,   3.,   4.,
          0.,   1.,   4.,   9.,  16.])

In [20]:
x = list(range(1000))
plt.plot(x, y)
plt.show()